#file: noinspection SpellCheckingInspection
networks:
  dev:
    driver: bridge

services:
  vinsj:
    container_name: vinsj
    image: ${DOCKER_REGISTRY-}vinsj
    build:
      context: .
      dockerfile: Vinsj/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - vinsjdb
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=vinsjdb;Port=5432;Database=NostedDataBase; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  vinsjdb:
    container_name: vinsjdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NostedDataBase
    ports:
      - "5433:5432"
    restart: always